version: '3.5'

services:

  mongodb:
    container_name: mysql_benchmark_dev
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mysql_benchmark"
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
